Project sturdy {
  database_type: 'PostgreSQL'
  Note: '''
  # `sturdy`
  A research study database.
  '''
}
// https://dbdiagram.io/d/sturdy-672d401ee9daa85acab74544
// https://dbdocs.io/mike.p.doc.71/sturdy?view=table_structure


Table study {
   id integer [primary key]
   type study_type
}

Table question {
   id integer [primary key]
   study integer [ref: <> study.id]
}

Table hypothesis {
   id integer [primary key]
   question integer [ref: <> question.id]
}

Table design {
   id integer [primary key]
   hypothesis integer [ref: <> hypothesis.id]
}

Table treatment {
   id integer [primary key]
   design integer [ref: <> design.id]
}

Table measurement {
   id integer [primary key]
   treatment integer [ref: <> treatment.id]
}

Table result {
   id integer [primary key]
   measurement integer [ref: <> measurement.id]
}

Table conclusion {
   id integer [primary key]
   conclusion integer [ref: <> result.id]
}

Table assessment {
   id integer [primary key]
}


enum study_type {
   performance
}

TableGroup conceptual_model {
   study
   question
   hypothesis
   design
   treatment
   measurement
   result
   conclusion
}
